version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=pollen8_db
      - DB_USER=pollen8_user
      - DB_PASSWORD=pollen8_password
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://mongo:27017/pollen8
      - JWT_SECRET=${JWT_SECRET}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_VERIFY_SERVICE_SID=${TWILIO_VERIFY_SERVICE_SID}
    depends_on:
      - postgres
      - redis
      - mongo
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=pollen8_db
      - POSTGRES_USER=pollen8_user
      - POSTGRES_PASSWORD=pollen8_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  postgres_data: {}
  redis_data: {}
  mongo_data: {}

networks:
  default:
    name: pollen8_network